### ISSUE TITLE
패키지 구조 변경

### ISSUE THREAD

**Issue by gu-sil** [eeeeweeee/Gamenawa#12]
현재 패키지 구조는 도메인 중심이나 너무 분류가 안돼있는 상황
```
/games
    Game
    GameScore
    IGameController
    IGameService
    ...
/util
    JsonParser
    ...
```

변경안
```
/games
    /controller
    /service
    /dto
/util
    /json
```

**Comment by Rabongbong** [comment]
/games 폴더 상위에 domain 폴더를 만들어서 안에 넣는건 어때?
나중에 error handler나 log나 interceptor 같은 경우는 global 폴더에 넣는 식으로 만들어도 좋을꺼 같아 
그럴러면 각 domain 별 기능과 전체 적용 되는 기능은 /global로 나누면 어떨까 해
